---
- name: Creare Masina Virtuala in OpenShift
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    vm_name: "test-vm-ansible"
    target_ns: "test"

  tasks:
    - name: Creeaza resursa VM
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: "{{ vm_name }}"
            namespace: "{{ target_ns }}"
          spec:
            running: true # Aceasta porneste VM-ul imediat
            template:
              spec:
                domain:
                  devices:
                    disks:
                      - disk:
                          bus: virtio
                        name: containerdisk
                  resources:
                    requests:
                      memory: 2Gi
                volumes:
                  - name: containerdisk
                    containerdisk:
                      image: quay.io/containerdisks/fedora:latest # Imagine gata de boot
