---
- name: Creare Masina Virtuala in OpenShift
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Task VM Final
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: test-vm-ansible
            namespace: test
          spec:
            running: true
            template:
              spec:
                domain:
                  devices:
                    disks:
                      - disk:
                          bus: virtio
                        name: disk0
                volumes:
                  - name: disk0
                    containerDisk:
                      image: quay.io/containerdisks/fedora:latest
