---
- name: Creare Masina Virtuala in OpenShift
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Task VM
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: test-vm-ansible
            namespace: test
          spec:
            running: true
            template:
              spec:
                domain:
                  devices:
                    disks:
                    - disk:
                        bus: virtio
                      name: rootv
                  resources:
                    requests:
                      memory: 2Gi
                volumes:
                - name: rootv
                  containerdisk:
                    image: quay.io/containerdisks/fedora:latest
